//
// Created by VitorMM on 7/27/26.
//

#ifndef MELONDS_PLUGINLANGUAGE_H
#define MELONDS_PLUGINLANGUAGE_H

#include <array>

namespace Plugins
{

struct Language
{
    int dsCode;
    char code[6]; // BCP 47/IETF
    char englishName[40];
    char name[60];
};

inline constexpr std::array<Language, 140> languages{{
    {1, "en",   "English",              "English"},
    {0, "jp",   "Japanese",             "日本語"}, // yes, we wrote 'jp' by mistake
    {2, "fr",   "French",               "Français"},
    {3, "de",   "German",               "Deutsch"},
    {4, "it",   "Italian",              "Italiano"},
    {5, "es",   "Spanish",              "Español"},
    {1, "zh",   "Chinese",              "中文"},
    {1, "af",   "Afrikaans",            "Afrikaans"},
    {1, "am",   "Amharic",              "አማርኛ"},
    {1, "ar",   "Arabic",               "العربية"},
    {1, "arn",  "Mapudungun",           "Mapudungun"},
    {1, "ary",  "Moroccan Arabic",      "الدارجة المغربية"},
    {1, "as",   "Assamese",             "অসমীয়া"},
    {1, "az",   "Azerbaijani",          "Azərbaycan"},
    {1, "ba",   "Bashkir",              "Башҡорт"},
    {1, "be",   "Belarusian",           "Беларуская"},
    {1, "bg",   "Bulgarian",            "Български"},
    {1, "bn",   "Bengali",              "বাংলা"},
    {1, "bo",   "Tibetan",              "བོད་ཡིག"},
    {1, "br",   "Breton",               "Brezhoneg"},
    {1, "bs",   "Bosnian",              "Bosanski/Босански"},
    {1, "ca",   "Catalan",              "Català"},
    {1, "ckb",  "Central Kurdish",      "کوردیی ناوەندی"},
    {1, "co",   "Corsican",             "Corsu"},
    {1, "cs",   "Czech",                "Čeština"},
    {1, "cy",   "Welsh",                "Cymraeg"},
    {1, "da",   "Danish",               "Dansk"},
    {1, "de",   "German",               "Deutsch"},
    {1, "dsb",  "Lower Sorbian",        "Dolnoserbšćina"},
    {1, "dv",   "Divehi",               "ދިވެހިބަސް"},
    {1, "el",   "Greek",                "Ελληνικά"},
    {1, "en",   "English",              "English"},
    {1, "es",   "Spanish",              "Español"},
    {1, "et",   "Estonian",             "Eesti"},
    {1, "eu",   "Basque",               "Euskara"},
    {1, "fa",   "Persian",              "فارسى"},
    {1, "fi",   "Finnish",              "Suomi"},
    {1, "fil",  "Filipino",             "Filipino"},
    {1, "fo",   "Faroese",              "Føroyskt"},
    {1, "fr",   "French",               "Français"},
    {1, "fy",   "Frisian",              "Frysk"},
    {1, "ga",   "Irish",                "Gaeilge"},
    {1, "gd",   "Scottish Gaelic",      "Gàidhlig"},
    {1, "gil",  "Gilbertese",           "Taetae Ni Kiribati"},
    {1, "gl",   "Galician",             "Galego"},
    {1, "gsw",  "Swiss German",         "Schweizerdeutsch"},
    {1, "gu",   "Gujarati",             "ગુજરાતી"},
    {1, "ha",   "Hausa",                "Hausa"},
    {1, "he",   "Hebrew",               "עברית"},
    {1, "hi",   "Hindi",                "हिंदी"},
    {1, "hr",   "Croatian",             "Hrvatski"},
    {1, "hsb",  "Upper Sorbian",        "Hornjoserbšćina"},
    {1, "hu",   "Hungarian",            "Magyar"},
    {1, "hy",   "Armenian",             "Հայերեն"},
    {1, "id",   "Indonesian",           "Bahasa Indonesia"},
    {1, "ig",   "Igbo",                 "Igbo"},
    {1, "ii",   "Yi",                   "ꆈꌠꁱꂷ"},
    {1, "is",   "Icelandic",            "Íslenska"},
    {1, "it",   "Italian",              "Italiano"},
    {1, "iu",   "Inuktitut",            "Inuktitut/ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕ)"},
    {1, "ka",   "Georgian",             "ქართული"},
    {1, "kk",   "Kazakh",               "Қазақша"},
    {1, "kl",   "Greenlandic",          "Kalaallisut"},
    {1, "km",   "Khmer",                "ខ្មែរ"},
    {1, "kn",   "Kannada",              "ಕನ್ನಡ"},
    {1, "ko",   "Korean",               "한국어"},
    {1, "kok",  "Konkani",              "कोंकणी"},
    {1, "ku",   "Kurdish",              "Kurdî/کوردی"},
    {1, "ky",   "Kyrgyz",               "Кыргыз"},
    {1, "lb",   "Luxembourgish",        "Lëtzebuergesch"},
    {1, "lo",   "Lao",                  "ລາວ"},
    {1, "lt",   "Lithuanian",           "Lietuvių"},
    {1, "lv",   "Latvian",              "Latviešu"},
    {1, "mi",   "Māori",                "Reo Māori"},
    {1, "mk",   "Macedonian",           "Македонски Јазик"},
    {1, "ml",   "Malayalam",            "മലയാളം"},
    {1, "mn",   "Mongolian",            "Монгол Хэл/ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ"},
    {1, "moh",  "Mohawk",               "Kanien'kéha"},
    {1, "mr",   "Marathi",              "मराठी"},
    {1, "ms",   "Malay",                "Bahasa Malaysia"},
    {1, "mt",   "Maltese",              "Malti"},
    {1, "my",   "Burmese",              "မြန်မာဘာသာ"},
    {1, "nb",   "Norwegian (Bokmål)",   "Norsk (Bokmål)"},
    {1, "ne",   "Nepali",               "नेपाली (नेपाल)"},
    {1, "nl",   "Dutch",                "Nederlands"},
    {1, "nn",   "Norwegian (Nynorsk)",  "Norsk (Nynorsk)"},
    {1, "no",   "Norwegian",            "Norsk"},
    {1, "oc",   "Occitan",              "Occitan"},
    {1, "or",   "Odia",                 "ଓଡ଼ିଆ"},
    {1, "pap",  "Papiamento",           "Papiamentu"},
    {1, "pa",   "Punjabi",              "ਪੰਜਾਬੀ/پنجابی"},
    {1, "pl",   "Polish",               "Polski"},
    {1, "prs",  "Dari",                 "درى"},
    {1, "ps",   "Pashto",               "پښتو"},
    {1, "pt",   "Portuguese",           "Português"},
    {1, "pt-br","Brazilian Portuguese", "Português (Brasil)"},
    {1, "quc",  "K'iche",               "K'iche"},
    {1, "qu",   "Quechua",              "Runasimi"},
    {1, "rm",   "Romansh",              "Rumantsch"},
    {1, "ro",   "Romanian",             "Română"},
    {1, "ru",   "Russian",              "Русский"},
    {1, "rw",   "Kinyarwanda",          "Kinyarwanda"},
    {1, "sa",   "Sanskrit",             "संस्कृत"},
    {1, "sah",  "Yakut",                "Саха"},
    {1, "sd",   "Sindhi",               "سِنڌِي"},
    {1, "se",   "Sami (Northern)",      "Davvisámegiella"},
    {1, "si",   "Sinhala",              "සිංහල"},
    {1, "sk",   "Slovak",               "Slovenčina"},
    {1, "sl",   "Slovenian",            "Slovenščina"},
    {1, "sma",  "Sami (Southern)",      "Åarjelsaemiengiele"},
    {1, "smj",  "Sami (Lule)",          "Julevusámegiella"},
    {1, "smn",  "Sami (Inari)",         "Sämikielâ"},
    {1, "sms",  "Sami (Skolt)",         "Sääʹmǩiõll"},
    {1, "sq",   "Albanian",             "Shqip"},
    {1, "sr",   "Serbian",              "Srpski/Српски"},
    {1, "st",   "Sesotho",              "Sesotho"},
    {1, "sv",   "Swedish",              "Svenska"},
    {1, "sw",   "Kiswahili",            "Kiswahili"},
    {1, "syc",  "Syriac",               "ܣܘܪܝܝܐ"},
    {1, "ta",   "Tamil",                "தமிழ்"},
    {1, "te",   "Telugu",               "తెలుగు"},
    {1, "tg",   "Tajik",                "Тоҷикӣ"},
    {1, "th",   "Thai",                 "ไทย"},
    {1, "tk",   "Turkmen",              "Türkmençe"},
    {1, "tl",   "Tagalog",              "Tagalog"},
    {1, "tn",   "Tswana",               "Setswana"},
    {1, "tr",   "Turkish",              "Türkçe"},
    {1, "tt",   "Tatar",                "Татарча"},
    {1, "tzm",  "Tamazight",            "Tamazight"},
    {1, "ug",   "Uyghur",               "ئۇيغۇرچە"},
    {1, "uk",   "Ukrainian",            "Українська"},
    {1, "ur",   "Urdu",                 "اُردو"},
    {1, "uz",   "Uzbek",                "Uzbek/Ўзбек"},
    {1, "vi",   "Vietnamese",           "Tiếng Việt"},
    {1, "wo",   "Wolof",                "Wolof"},
    {1, "xh",   "Xhosa",                "Isixhosa"},
    {1, "yi",   "Yiddish",              "יידיש"},
    {1, "yo",   "Yoruba",               "Yoruba"},
    {1, "zu",   "Zulu",                 "Isizulu"}
}};

}

#endif //MELONDS_PLUGINLANGUAGE_H
